server:
  port: 8081

spring:
  application:
    name: service-provider  # 服务名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # Nacos地址
dubbo:
  application:
    name: service-provider
  registry:
    address: nacos://127.0.0.1:8848
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/