server:
  port: 8081

spring:
  application:
    name: service-provider  # 服务名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # Nacos地址

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/